name: Run Keyword Generator

on:
  workflow_dispatch:  # 👈 Manual trigger from GitHub UI

jobs:
  generate_keyword:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run keyword generator
        run: python keyword_engine.py
